version: "3.4"

services:
  # App
  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      target: app_prod
    restart: unless-stopped

  # Nginx
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
      target: nginx_prod
    ports:
      - 8080:80
    restart: unless-stopped
