version: "3.4"

services:
  # Nginx
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
      target: nginx_prod
    environment:
      - TZ=Europe/Moscow
    ports:
      - 8080:80
    restart: unless-stopped

  # App
  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      target: app_prod
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
