services:
  # Nginx
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - 8080:80
    volumes:
      - ./public:/app/public
      - ./var/cache:/app/var/cache
    restart: unless-stopped

  # App
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    tmpfs:
      - /tmp
    restart: unless-stopped
