version: '3'

services:
  # Nginx
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile.prod
    ports:
      - 8080:80
    restart: always

  # App
  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile.prod
    tmpfs:
      - /tmp
    restart: always
