version: "3.4"

services:
  # App
  app:
    build:
      target: app_dev
    volumes:
      - ./:/app:rw,cached

  # Nginx
  nginx:
    build:
      target: nginx_dev
    volumes:
      - ./public:/app/public:ro
